server:
  error:
    include-exception: false      # Response 에 Exception 을 표시할지
    include-message: always       # Response 에 Exception Message 를 표시할지 (never | always | on_param)
    include-stacktrace: never  # Response 에 Stack Trace 를 표시할지 (never | always | on_param) on_trace_params 은 deprecated
    whitelabel.enabled: true      # 에러 발생 시 Spring 기본 에러 페이지 노출 여부
  tomcat:
    connection-timeout: 5s   # 연결 시도 시간
#    keep-alive-timeout: 10s  # 요청부터 응답가지 유지하는 시간

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  #h2
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:product;MODE=MySQL;
    username: sa
    password:

  jpa:
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:db/data.sql

logging:
  level:
    sam.song.product.common.logTrace: DEBUG